import {Income} from './finance';
import {MapField,fullMapAddress,type MapPoint} from './map-field';
import {FoodArt,ChefArt} from './art';
import{useState,useEffect}from'react';import{Button,Input,InputNumber,Select,Checkbox,Alert,Empty}from'antd';import{api,money,time,labels,type Row}from'./api';import{useData,Field,QueryState,UploadField,status,options,type Run}from'./ui';import{Booking}from'./booking';
export function Discover({run,onOrders}:{run:Run,onOrders:()=>void}){
 const[cuisine,setCuisine]=useState('全部'),[search,setSearch]=useState(''),[sort,setSort]=useState('default'),[onlyFavorites,setOnlyFavorites]=useState(false),[selected,setSelected]=useState<Row|null>(null),[location,setLocation]=useState<Row|null>(()=>JSON.parse(localStorage.getItem('home-chef-location')??'null'));
 useEffect(()=>{const update=()=>setLocation(JSON.parse(localStorage.getItem('home-chef-location')??'null'));window.addEventListener('service-location-changed',update);return()=>window.removeEventListener('service-location-changed',update);},[]);
 const chefs=useData('/chefs?search='+encodeURIComponent(search.trim())+'&cuisine='+encodeURIComponent(cuisine)+'&sort='+sort+(location?'&latitude='+location.latitude+'&longitude='+location.longitude:'')),favorites=useData('/favorites');
 const rows=(chefs.data??[]).filter((c:Row)=>!onlyFavorites||favorites.data?.some((f:Row)=>f.chefId===c.id));
 return <><section className="hero"><div><span className="eyebrow">A GOOD MEAL, AT HOME</span><h1>家的味道，<br/><em>交给好厨师。</em></h1><p>从家常晚餐到团圆家宴，认证厨师带着手艺来到你家。<br/>你只需选好时间，等一桌热气腾腾。</p><a href="#chefs" className="hero-link">挑选下一餐的好手艺 ↗</a></div><div className="hero-food"><span className="food-circle"><FoodArt/></span><div className="food-note">新鲜下厨 · 趁热上桌<br/><strong>每一餐，都值得认真对待</strong></div></div></section><div className="benefits"><span>01　认证与健康审核</span><span>02　报价透明 · 先确认后支付</span><span>03　履约记录 · 售后可追溯</span></div><section id="chefs"><div className="section-head"><div><span className="eyebrow">MEET YOUR CHEF</span><h2>附近的好厨师</h2></div><Input aria-label="搜索服务者" placeholder="搜索名字、菜系、套餐" value={search} onChange={e=>setSearch(e.target.value)}/><Select aria-label="排序" value={sort} onChange={setSort} options={[{value:'default',label:'默认排序'},{value:'price_asc',label:'价格从低到高'},{value:'price_desc',label:'价格从高到低'},...(location?[{value:'distance',label:'距离从近到远'}]:[])]}/><Checkbox checked={onlyFavorites} onChange={e=>setOnlyFavorites(e.target.checked)}>只看收藏</Checkbox><Select aria-label="菜系筛选" value={cuisine} onChange={setCuisine} options={options(['全部','湘菜','粤菜','川菜','鲁菜','苏菜','浙菜','闽菜','徽菜','家常菜'])}/></div><QueryState q={chefs}/><div className="chef-grid">{rows.map((c:Row,i:number)=><article className="chef-card" key={c.id}><div className={'chef-cover cover-'+i%3}><div className="chef-avatar"><ChefArt/></div><span>{c.cuisines.join(' · ')}</span></div><div className="chef-info"><div className="row"><h3>{c.name}</h3>{status(c.status)}</div><p>{c.bio}</p><div className="muted">健康材料有效至 {new Date(c.healthValidUntil).toLocaleDateString()}</div><div className="card-bottom"><div><strong>{c.packages.length?money(Math.min(...c.packages.map((p:Row)=>p.serviceFen))):'待发布'}</strong><small> / 服务起</small></div><Button type="primary" disabled={!c.packages.length} onClick={()=>setSelected(c)}>选套餐</Button></div><Button type="text" size="small" onClick={()=>void run(()=>api('/favorites/'+c.id,{}))}>{favorites.data?.some((f:Row)=>f.chefId===c.id)?'♥ 已收藏':'♡ 收藏厨师'}</Button></div></article>)}</div>{!rows.length&&!chefs.isLoading&&<Empty description="当前条件暂无可预约服务者"/>}</section><Booking chef={selected} close={()=>setSelected(null)} run={run} onDone={onOrders}/></>;
}
export function Addresses({run}:{run:Run}){
 const q=useData('/addresses'),rules=useData('/rules'),[point,setPoint]=useState<MapPoint|null>(null),[door,setDoor]=useState(''),[f,setF]=useState<Row>({label:'家',regionCode:''});
 const regions:Row[]=(rules.data?.regions??[]).filter((r:Row)=>r.active);
 useEffect(()=>{const active:Row[]=(rules.data?.regions??[]).filter((r:Row)=>r.active);setF(current=>({...current,regionCode:active.some(r=>r.code===current.regionCode)?current.regionCode:active[0]?.code??''}));},[rules.data]);
 return <><h1>服务地址</h1><p className="muted">从地图选择服务位置，再补充楼栋、单元和门牌号。完整地址仅向本人及满足条件的接单厨师开放。</p><div className="two-col"><div><QueryState q={q}/>{q.data?.map((a:Row)=><article className="panel" key={a.id}><h3>{a.label}</h3><p>{a.fullText}</p><small>{a.maskedText}</small><Button danger type="text" onClick={()=>void run(()=>api('/addresses/'+a.id,undefined,'DELETE'))}>删除</Button></article>)}</div><div className="panel"><h2>添加地址</h2><Field label="地址名称"><Input value={f.label} onChange={e=>setF({...f,label:e.target.value})}/></Field><Field label="服务片区"><Select placeholder="暂无开放的服务片区" value={f.regionCode||undefined} onChange={v=>setF({...f,regionCode:v})} options={rules.data?.regions.filter((r:Row)=>r.active).map((r:Row)=>({value:r.code,label:r.name}))}/></Field><MapField value={point} onChange={p=>{setPoint(p);setDoor('');}}/><Field label="楼栋 / 单元 / 门牌号"><Input placeholder="例如：3栋2单元602室" value={door} onChange={e=>setDoor(e.target.value)}/></Field><p className="muted">当前仅开放长沙服务范围。能在地图找到地址，不代表该地址已开放服务。</p><Button type="primary" disabled={!regions.some(r=>r.code===f.regionCode)||!point||!door.trim()} onClick={()=>void run(async()=>{if(!point)return;await api('/addresses',{...f,...point,fullText:fullMapAddress(point,door)});setPoint(null);setDoor('');})}>保存地址</Button></div></div></>;
}
export function Wallet({run}:{run:Run}){const coupons=useData('/coupons'),notes=useData('/notifications'),rules=useData('/rules');return <><h1>优惠与消息</h1>{rules.data?.couponEnabled?<Button type="primary" onClick={()=>void run(()=>api('/coupons',{}))}>领取新人券</Button>:<p className="muted">暂无可领取的优惠活动</p>}<div className="two-col space"><section><h2>我的优惠券</h2><QueryState q={coupons}/>{coupons.data?.map((c:Row)=><div className="coupon" key={c.id}><strong>{money(c.amountFen)}</strong><div>{c.label}<p>满{money(c.minFen)}可用 · 不可叠加</p><small>{c.status} · {time(c.expiresAt)}到期</small></div></div>)}</section><section><h2>站内消息</h2><QueryState q={notes}/>{notes.data?.map((n:Row)=><div className="panel" key={n.id}><p>{n.body}</p><small>{time(n.createdAt)}</small>{!n.readAt&&<Button type="link" onClick={()=>void run(()=>api('/notifications/'+n.id,{}))}>标为已读</Button>}</div>)}{notes.data?.length===0&&<Empty description="暂时没有新消息"/>}</section></div></>;}
export function Chef({run}:{run:Run}){
 const q=useData('/chef/profile'),rules=useData('/rules'),[f,setF]=useState<Row>({bio:'',cuisines:['湘菜'],regionCode:'',healthValidUntil:'',agreement:false}),[pkg,setPkg]=useState<Row>({name:'四菜一汤',description:'备菜、烹饪、装盘、基础灶台清理与餐具归位',serviceFen:19800}),[slot,setSlot]=useState<Row>({});
 const[servicePoint,setServicePoint]=useState<MapPoint|null>(null);
 const regions:Row[]=(rules.data?.regions??[]).filter((r:Row)=>r.active);
 useEffect(()=>{const active:Row[]=(rules.data?.regions??[]).filter((r:Row)=>r.active);setF(current=>({...current,regionCode:active.some(r=>r.code===current.regionCode)?current.regionCode:active[0]?.code??''}));},[rules.data]);
 const editable=!q.data||['PENDING_REVIEW','REJECTED'].includes(q.data.status);
 return <><h1>厨师工作台</h1>{q.data&&<Income/>}<QueryState q={q}/>{q.data&&<><Alert type="info" message={(labels[q.data.status]??q.data.status)+' · '+(q.data.data.reviewReason??'健康材料有效期：'+time(q.data.healthValidUntil))}/><div className="two-col space"><section className="panel"><h2>套餐管理</h2>{q.data.packages.map((p:Row)=><p key={p.id}>{p.name} · {money(p.serviceFen)}</p>)}<Field label="名称"><Input value={pkg.name} onChange={e=>setPkg({...pkg,name:e.target.value})}/></Field><Field label="包含的服务"><Input.TextArea value={pkg.description} onChange={e=>setPkg({...pkg,description:e.target.value})}/></Field><Field label="价格（元）"><InputNumber value={pkg.serviceFen/100} onChange={v=>setPkg({...pkg,serviceFen:Math.round(Number(v)*100)})}/></Field><Button onClick={()=>void run(()=>api('/chef/packages',pkg))}>新增套餐</Button></section><section className="panel"><h2>可服务档期</h2><p className="muted">可用时间须包含服务前后各60分钟缓冲。</p>{q.data.schedules.map((s:Row)=><p key={s.id}>{time(s.startsAt)} — {time(s.endsAt)}</p>)}<Field label="开始"><input type="datetime-local" onChange={e=>setSlot({...slot,startsAt:e.target.value})}/></Field><Field label="结束"><input type="datetime-local" onChange={e=>setSlot({...slot,endsAt:e.target.value})}/></Field><Button onClick={()=>void run(()=>api('/chef/schedules',{startsAt:new Date(slot.startsAt).toISOString(),endsAt:new Date(slot.endsAt).toISOString()}))}>添加档期</Button></section></div></>}{editable&&<section className="panel narrow"><h2>{q.data?'补充并重新提交材料':'申请成为厨临门厨师'}</h2><Field label="服务片区"><Select placeholder="暂无开放的服务片区" value={f.regionCode||undefined} onChange={regionCode=>setF({...f,regionCode})} options={regions.map(r=>({value:r.code,label:r.name}))}/></Field><Field label="擅长菜系"><Select mode="multiple" value={f.cuisines} onChange={v=>setF({...f,cuisines:v})} options={options(['湘菜','粤菜','川菜','鲁菜','苏菜','浙菜','闽菜','徽菜'])}/></Field><MapField label="地图选择接单出发位置" value={servicePoint} onChange={setServicePoint}/><p className="muted">用于匹配附近订单，不公开完整出发地址。</p><Field label="自我介绍"><Input.TextArea value={f.bio} onChange={e=>setF({...f,bio:e.target.value})}/></Field><Field label="健康证有效期"><input type="date" onChange={e=>setF({...f,healthValidUntil:e.target.value})}/></Field><UploadField label="健康证明" run={run} onUploaded={id=>setF({...f,healthAssetId:id})}/><Checkbox checked={f.agreement} onChange={e=>setF({...f,agreement:e.target.checked})}>已阅读服务边界，同意审核与前三单试岗</Checkbox><Button block type="primary" className="space" disabled={!regions.some(r=>r.code===f.regionCode)||!servicePoint} onClick={()=>void run(()=>api('/chef/profile',{...f,latitude:servicePoint?.latitude,longitude:servicePoint?.longitude,coordinateSystem:'GCJ02'}))}>提交审核</Button></section>}</>;
}