import{useState,useEffect,useRef}from'react';import{Button,Modal,Input,InputNumber,Select,Alert,Checkbox,Empty}from'antd';import{api,money,time,type Row}from'./api';import{useData,Field,QueryState,UploadField,status,type Run}from'./ui';
export function Orders({user,run,staff}:{user:Row,run:Run,staff:boolean}){
 const q=useData('/orders'),[selected,setSelected]=useState<Row|null>(null),[pull,setPull]=useState(0),start=useRef<number|null>(null),distance=useRef(0);
 useEffect(()=>{const focus=()=>void q.refetch();window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[]);
 useEffect(()=>{if(selected){const current=q.data?.find((o:Row)=>o.id===selected.id);if(current)setSelected(current);}},[q.data]);
 return <><div className="section-head"><div><span className="eyebrow">EVERY MEAL, WELL CARED FOR</span><h1>{staff?'订单管理':'我的订单'}</h1></div><span className="muted">{q.isFetching?'更新中…':pull>=65?'松开刷新':'下拉刷新'}</span></div><QueryState q={q}/>{q.data?.length===0&&<Empty description="还没有订单，去发现一位好厨师吧"/>}<div className="order-list" onTouchStart={e=>{if(window.scrollY<=0&&!selected)start.current=e.touches[0].clientY;}} onTouchMove={e=>{if(start.current!==null){distance.current=Math.max(0,Math.min(100,e.touches[0].clientY-start.current));setPull(distance.current);}}} onTouchEnd={()=>{const d=distance.current;start.current=null;distance.current=0;setPull(0);if(d>=65&&!q.isFetching)void q.refetch();}}>{q.data?.map((o:Row)=><article className="panel order-card" key={o.id} tabIndex={0} role="button" aria-label={'详情 '+o.details.packageName} onClick={()=>setSelected(o)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(o);}}}><div className="row"><small>{o.id}</small>{status(o.contractStatus)}</div><h3>{o.details.packageName}</h3><p>{time(o.details.startsAt)} · {o.details.guests}人 · {o.details.maskedAddress}</p><div className="row"><span>{status(o.fulfillmentStatus)} {status(o.paymentStatus)}</span><strong>{money(o.totalFen)}</strong></div><span className="space">详情 →</span></article>)}</div><OrderDetail order={selected} user={user} close={()=>setSelected(null)} run={run}/></>;
}
function OrderDetail({order:o,user,close,run}:{order:Row|null,user:Row,close:()=>void,run:Run}){
 const[note,setNote]=useState(''),[photo,setPhoto]=useState(''),[receipt,setReceipt]=useState(''),[actual,setActual]=useState(0),[chat,setChat]=useState('');
 const messages=useData('/orders/'+o?.id+'/messages',!!o&&(o?.customerId===user.id||user.roles.includes('CHEF'))&&o?.contractStatus==='ACCEPTED');
 useEffect(()=>{setNote('');setPhoto('');setReceipt('');setActual((o?.details.ingredientFen??0)/100);},[o?.id]);
 if(!o)return null;
 const customer=o.customerId===user.id,chef=user.roles.includes('CHEF')&&!customer,action=(name:string,b:Row={})=>run(()=>api('/orders/'+o.id+'/'+name,b));
 const steps:Row={READY:['depart','记录出发'],DEPARTED:['arrive','到达签到'],ARRIVED:['start','开始服务'],SERVING:['complete','提交完成凭证']};
 return <Modal open title={o.details.packageName} onCancel={close} footer={null} width={820}><div className="status-grid">{[['合同',o.contractStatus],['支付',o.paymentStatus],['履约',o.fulfillmentStatus],['费用',o.feeStatus],['售后',o.aftersaleStatus],['结算',o.settlementStatus],['评价',o.reviewStatus]].map(([k,v])=><div key={k}><small>{k}</small>{status(v)}</div>)}</div><Alert type="warning" message={'过敏提醒：'+o.details.allergens}/><p className="space">{time(o.details.startsAt)} — {time(o.details.endsAt)} · {o.details.guests}人</p><p>地址：{o.details.fullAddress??o.details.maskedAddress+'（未解锁详细地址）'}</p><p>厨房：{o.details.kitchen} · 口味：{o.details.taste}</p><p>应付 {money(o.totalFen)} / 累计实收 {money(o.receivedFen)} / 已退 {money(o.refundedFen)} / 待补 {money(o.balanceFen)}</p>{!o.sandbox&&o.feeStatus==='AWAITING_PAYMENT'&&<Alert type="info" message="请在微信小程序中打开本订单支付尾款。"/>}{o.payments?.filter((p:any)=>p.kind==='REFUND').map((p:any)=><p key={p.id}>退款 {money(p.amountFen)}：{p.status==='SUCCEEDED'?'已原路退回':p.status==='FAILED'?'退款异常，请联系客服':'处理中'}</p>)}{o.policy&&<p>保单：{o.policy.status}</p>}{o.contractStatus==='PENDING_PAYMENT'&&<Alert type="info" message="订单已保存，请在微信小程序中打开本订单付款；支付未开通时无法扣款，付款期限过后自动取消。"/>}{o.contractStatus==='PENDING_ACCEPTANCE'&&<p>接单截止：{time(o.details.acceptanceDeadline)}</p>}
 <div className="actions">{chef&&o.contractStatus==='PENDING_ACCEPTANCE'&&<Button type="primary" onClick={()=>void action('accept')}>接单 / 抢单</Button>}{customer&&o.contractStatus==='ACCEPTED'&&<Button onClick={()=>void action('address-consent')}>提前授权地址</Button>}{customer&&o.fulfillmentStatus==='AWAITING_CONFIRMATION'&&<><Button onClick={()=>void action('confirm-fees')}>确认最终费用</Button><Button type="primary" onClick={()=>void action('confirm')}>确认服务完成</Button></>}{customer&&o.feeStatus==='AWAITING_CONFIRMATION'&&o.confirmedAt&&<Button onClick={()=>void action('confirm-fees')}>确认最终费用</Button>}{customer&&o.sandbox&&o.feeStatus==='AWAITING_PAYMENT'&&<Button type="primary" onClick={()=>void action('balance',{idempotencyKey:crypto.randomUUID()})}>沙箱支付尾款 {money(o.balanceFen)}</Button>}{o.sandbox&&user.roles.includes('FINANCE')&&o.settlementStatus==='PENDING'&&<Button type="primary" onClick={()=>void run(()=>api('/ops/settlements/'+o.id,{}))}>执行沙箱结算</Button>}</div>
 {chef&&steps[o.fulfillmentStatus]&&<section className="panel"><h3>厨师履约</h3><Field label="履约说明"><Input.TextArea value={note} onChange={e=>setNote(e.target.value)}/></Field>{o.fulfillmentStatus==='SERVING'&&<><Field label="实际采购费（元）"><InputNumber min={0} max={o.details.ingredientFen/100} value={actual} onChange={v=>setActual(v??0)}/></Field><UploadField label="成品照片" orderId={o.id} onUploaded={setPhoto} run={run}/>{actual>0&&<UploadField label="采购小票" orderId={o.id} onUploaded={setReceipt} run={run}/>}</>}<Button type="primary" onClick={()=>void action('fulfill',{action:steps[o.fulfillmentStatus][0],evidence:note,assetId:photo,receiptId:receipt,actualIngredientFen:Math.round(actual*100)})}>{steps[o.fulfillmentStatus][1]}</Button></section>}
 <section className="panel"><h3>订单沟通与售后</h3><Field label="原因 / 说明"><Input.TextArea value={note} onChange={e=>setNote(e.target.value)} placeholder="取消、售后或报案时，请填写具体说明"/></Field><div className="actions">{(customer||chef)&&['PENDING_PAYMENT','PENDING_ACCEPTANCE','ACCEPTED'].includes(o.contractStatus)&&<Button danger onClick={()=>void action('cancel',{reason:note||'取消预约'})}>申请取消</Button>}{(customer||chef)&&<><Button onClick={()=>void action('tickets',{reason:note})}>申请售后</Button><Button danger onClick={()=>void action('tickets',{reason:note,incident:true})}>安全事故工单</Button></>}{customer&&o.sandbox&&<Button onClick={()=>void action('insurance-claim',{reason:note})}>保险报案（沙箱）</Button>}</div></section>
 {customer&&o.confirmedAt&&<ReviewForm order={o} action={action}/>}
 {(customer||chef)&&o.contractStatus==='ACCEPTED'&&<ChangeForm order={o} user={user} action={action}/>}
 {messages.data&&<section className="panel"><h3>订单聊天</h3><div className="chat">{messages.data.map((m:Row)=><p key={m.id} className={m.senderId===user.id?'mine':''}>{m.blocked?'【已拦截】':''}{m.body}<small>{time(m.createdAt)}</small></p>)}</div><div className="row"><Input value={chat} onChange={e=>setChat(e.target.value)} placeholder="请在平台内沟通，勿交换联系方式"/><Button onClick={()=>void run(async()=>{await api('/orders/'+o.id+'/messages',{body:chat});setChat('');})}>发送</Button></div></section>}
 <details><summary>订单时间线与审计</summary>{o.timeline?.map((e:Row,i:number)=><p key={i}><small>{time(e.createdAt)}</small> {e.action}</p>)}</details></Modal>;
}
function ReviewForm({order,action}:{order:Row,action:(n:string,b:Row)=>Promise<void>}){const[f,setF]=useState<Row>({taste:5,service:5,punctuality:5,body:'',anonymous:false});return <section className="panel"><h3>{order.reviewStatus==='REVIEWED'?'追加评价':'评价这次家宴'}</h3>{order.reviewStatus!=='REVIEWED'&&<div className="form-grid">{[['taste','口味'],['service','服务态度'],['punctuality','准时度']].map(([key,label])=><Field key={key} label={label}><InputNumber min={1} max={5} value={f[key]} onChange={v=>setF({...f,[key]:v})}/></Field>)}</div>}<Input.TextArea placeholder="写下你的用餐体验" value={f.body} onChange={e=>setF({...f,body:e.target.value})}/><Checkbox checked={f.anonymous} onChange={e=>setF({...f,anonymous:e.target.checked})}>匿名</Checkbox><Button onClick={()=>void action('reviews',order.reviewStatus==='REVIEWED'?{followup:f.body}:f)}>提交评价</Button></section>;}

function ChangeForm({order,user,action}:{order:Row,user:Row,action:(n:string,b:Row)=>Promise<void>}){
 const[f,setF]=useState<Row>({kind:'SCHEDULE',startsAt:'',reason:'',ingredientFen:order.details.ingredientFen+10000,menu:''}),pending=order.details.pendingChange;
 if(pending)return <section className="panel"><h3>待确认的订单变更</h3><p>{pending.reason}</p>{pending.kind==='SCHEDULE'&&<p>新时间：{time(pending.startsAt)}</p>}{pending.kind==='BUDGET'&&<p>采购增量：{money(pending.additionalFen)}，确认后将沙箱支付该增量。</p>}{pending.kind==='MENU'&&<p>{pending.menu}</p>}{pending.createdBy!==user.id?<div className="actions"><Button type="primary" onClick={()=>void action('changes',{action:'accept',changeId:pending.id})}>同意变更{pending.kind==='BUDGET'?'并沙箱支付':''}</Button><Button onClick={()=>void action('changes',{action:'reject',changeId:pending.id})}>拒绝变更</Button></div>:<p className="muted">等待另一方确认，现有订单仍按原约定执行。</p>}</section>;
 return <details className="panel"><summary>协商改约 / 菜单 / 采购增量</summary><Field label="变更类型"><Select value={f.kind} onChange={v=>setF({...f,kind:v})} options={[{value:'SCHEDULE',label:'改约时间'},{value:'MENU',label:'调整菜单'},...(user.roles.includes('CHEF')&&order.details.ingredientMode==='CHEF'?[{value:'BUDGET',label:'采购预算增量'}]:[])]}/></Field>{f.kind==='SCHEDULE'&&<Field label="新上门时间"><input type="datetime-local" step="1800" value={f.startsAt} onChange={e=>setF({...f,startsAt:e.target.value})}/></Field>}{f.kind==='BUDGET'&&<Field label="新的采购总预算（元）"><InputNumber min={order.details.ingredientFen/100} max={1000} value={f.ingredientFen/100} onChange={v=>setF({...f,ingredientFen:Math.round(Number(v)*100)})}/></Field>}{f.kind==='MENU'&&<Field label="新菜单"><Input.TextArea value={f.menu} onChange={e=>setF({...f,menu:e.target.value})}/></Field>}<Field label="变更原因"><Input value={f.reason} onChange={e=>setF({...f,reason:e.target.value})}/></Field><Button onClick={()=>void action('changes',{...f,action:'propose',...(f.kind==='SCHEDULE'?{startsAt:new Date(f.startsAt).toISOString()}:{})})}>提交双方确认</Button></details>;
}