import {useState,useEffect} from 'react';
import {View,Text,Button,Input,Picker} from '@tarojs/components';
import Taro from '@tarojs/taro';
import {api,money,names} from '../../api';
type R=Record<string,any>;
export function MealArt(){return <View className="meal-art"><View className="plate plate-one"><View className="greens"/><View className="tomatoes"/></View><View className="plate plate-two"><View className="rice"/></View><View className="chopsticks"/><Text className="art-note">家常餐桌 · 插画示意</Text></View>;}
export function Discovery({tab,onTab,onDetail,onBook,location,favorites,revision}:{tab:string,onTab:(v:string)=>void,onDetail:(c:R)=>void,onBook:(c:R,p:R)=>void,location:R|null,favorites:R[],revision:number}){
 const[filterOpen,setFilterOpen]=useState('');
 const[search,setSearch]=useState(''),[sort,setSort]=useState(0),[cuisine,setCuisine]=useState('全部'),[visible,setVisible]=useState<R[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const cuisines=['全部','湘菜','粤菜','川菜','鲁菜','苏菜','浙菜','闽菜','徽菜','家常菜'];
 const min=(c:R)=>Math.min(...c.packages.map((p:R)=>p.serviceFen));
 useEffect(()=>{let current=true;setLoading(true);setError('');const timer=setTimeout(()=>{const q='?search='+encodeURIComponent(search.trim())+'&cuisine='+encodeURIComponent(cuisine)+'&sort='+['default','price_asc','price_desc','distance'][sort]+(location?'&latitude='+location.latitude+'&longitude='+location.longitude:'');
 api('/chefs'+q).then(rows=>{if(current)setVisible(rows);}).catch(e=>{if(current){setVisible([]);setError(e.message);}}).finally(()=>{if(current)setLoading(false);});},250);return()=>{current=false;clearTimeout(timer);};},[search,sort,cuisine,location?.latitude,location?.longitude,revision]);
 const shown=tab==='favorites'?visible.filter(c=>favorites.some(f=>f.chefId===c.id)):visible;
 const packages=shown.flatMap(c=>c.packages.map((p:R)=>({c,p}))).sort((a,b)=>sort===1?a.p.serviceFen-b.p.serviceFen:sort===2?b.p.serviceFen-a.p.serviceFen:0);
 return <>
 {tab==='home'?<><View className="community-hero"><Text className="eyebrow">一餐家常，一份安心</Text><Text className="hero-title">忙了一天，<Text>回家吃顿热乎饭。</Text></Text><Text className="hero-copy">附近的人来做饭，把时间留给家人。</Text><Button className="primary hero-button" onClick={()=>onTab('find')}>找人来做饭 →</Button><MealArt/></View>
 <View className="entry-grid">{[['find','01','找人做饭','看看附近好手艺'],['packages','02','家常套餐','按一餐选服务'],['chef','03','做饭赚收入','让好手艺有回报']].map(([key,num,title,sub])=><View className="entry" key={key} onClick={()=>onTab(key)}><Text className="entry-num">{num}</Text><Text className="entry-title">{title}</Text><Text className="entry-sub">{sub}</Text></View>)}</View>
 <View className="trust-strip"><Text>先看服务范围</Text><Text>费用确认再下单</Text><Text>订单内沟通</Text></View><View className="section-row"><View><Text className="heading">附近的好厨师</Text><Text className="hint">家常手艺，慢慢了解再预约</Text></View><Text className="link" onClick={()=>onTab('find')}>查看全部 →</Text></View></>:<><View className="section-row"><View><Text className="heading">{tab==='find'?'找人做饭':tab==='favorites'?'我的收藏':'家常套餐'}</Text><Text className="hint">{location?.name??'选择位置，查看附近服务'}</Text></View><Text className="link" onClick={()=>onTab('home')}>返回首页</Text></View><View className="search-box"><Input placeholder="搜索名字、菜系、拿手菜" value={search} onInput={e=>setSearch(e.detail.value)}/>{search&&<Text onClick={()=>setSearch('')}>清除</Text>}</View><View className="filter-row"><Text onClick={()=>setFilterOpen(filterOpen==='sort'?'':'sort')}>{['默认排序','价格从低到高','价格从高到低','距离从近到远'][sort]} ▾</Text><Text onClick={()=>setFilterOpen(filterOpen==='cuisine'?'':'cuisine')}>{cuisine==='全部'?'全部菜系':cuisine} ▾</Text></View>{filterOpen==='sort'&&<View className="filter-options">{['默认排序','价格从低到高','价格从高到低',...(location?['距离从近到远']:[])].map((label,i)=><Text key={label} className={sort===i?'active':''} onClick={()=>{setSort(i);setFilterOpen('');}}>{label}</Text>)}</View>}{filterOpen==='cuisine'&&<View className="filter-options">{cuisines.map(c=><Text key={c} className={cuisine===c?'active':''} onClick={()=>{setCuisine(c);setFilterOpen('');}}>{c}</Text>)}</View>}</>}
 {tab==='packages'?<View className="package-grid">{packages.map(({c,p})=><View className="meal-card" key={p.id}><View className="package-art"><MealArt/></View><View className="meal-content"><Text className="heading">{p.name}</Text><Text className="hint" onClick={()=>onDetail(c)}>{c.name} · 查看服务者 →</Text><Text className="scope-copy">{p.description}</Text><Text className="price">{money(p.serviceFen)}<Text className="price-unit"> / 次服务</Text></Text><Text className="hint">食材自备时的服务费</Text><Button className="primary" onClick={()=>onBook(c,p)}>选这个套餐</Button></View></View>)}</View>:<View className={tab==='home'?'people-grid':'people-list'}>{shown.map((c,i)=><View className="person-card" key={c.id} onClick={()=>onDetail(c)}><View className={'person-art tone-'+i%3}><Text className="person-monogram">{c.name.slice(0,1)}</Text><Text className="person-art-label">家常饭 · {c.cuisines[0]||'用心做'}</Text></View><View className="person-content"><View className="section-row"><Text className="person-name">{c.name}</Text><Text className="small-status">{names[c.status]??c.status}</Text></View><Text className="cuisine-tags">{c.cuisines.join(' / ')}</Text><Text className="bio">{c.bio||'打开主页，了解服务套餐与范围。'}</Text><Text className="price">{c.packages.length?money(min(c)):'暂无套餐'}{c.packages.length>0&&<Text className="price-unit"> 起 / 次</Text>}</Text>{c.distanceM!==null&&<Text className="hint">距所选位置 {(c.distanceM/1000).toFixed(1)} 公里</Text>}<Text className="person-cta">了解手艺与服务 →</Text></View></View>)}</View>}
 {loading&&<Text className="hint">正在查询…</Text>}{error&&<Text className="error">{error}</Text>}{!loading&&!error&&!shown.length&&<View className="empty-state">{tab==='favorites'?'尚无符合当前条件的收藏。':'暂时没有符合条件的服务者，试试其他位置、名字或菜系。'}</View>}
 <View className="earn-banner" onClick={()=>onTab('chef')}><Text className="heading">把拿手家常菜，变成一份收入。</Text><Text>空闲时间由你安排，审核通过后接单。 →</Text></View>
 </>;
}
export function ChefDetail({chef,reviews,onBack,onBook,onFavorite,favorite,busy}:{chef:R,reviews:R[]|null,onBack:()=>void,onBook:(p:R)=>void,onFavorite:()=>void,favorite:boolean,busy:boolean}){
 const[tab,setTab]=useState('service');
 const avg=reviews?.length?(reviews.reduce((s,r)=>s+(r.taste+r.service+r.punctuality)/3,0)/reviews.length).toFixed(1):null;
 return <><View className="section-row"><Text className="link" onClick={onBack}>← 返回</Text><Text>服务者详情</Text><Text className="link" onClick={()=>{if(!busy)onFavorite();}}>{favorite?'已收藏 · 取消收藏':'收藏'}</Text></View><View className="profile-hero"><View className="profile-avatar">{chef.name.slice(0,1)}</View><Text className="hero-title">{chef.name}</Text><Text>{chef.cuisines.join(' · ')}</Text><Text className="hint">{chef.bio}</Text><Text className="small-status">{names[chef.status]} · {avg?avg+' 分（当前展示评价）':reviews===null?'评价加载中':'暂无评价，期待第一份反馈'}</Text></View><View className="trust-strip"><Text>提前预约</Text><Text>费用透明</Text><Text>服务范围先确认</Text></View><View className="detail-tabs">{[['service','服务套餐'],['about','手艺与评价']].map(([k,v])=><Text key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);if(process.env.TARO_ENV==='h5')document.getElementById(k==='service'?'chef-services':'chef-about')?.scrollIntoView({behavior:'smooth',block:'start'});else void Taro.pageScrollTo({selector:k==='service'?'#chef-services':'#chef-about',duration:250});}}>{v}</Text>)}</View>
 <View id="chef-services" className="card anchor-section"><Text className="heading">选一顿适合家里的饭</Text><Text className="hint">以下为人工服务费；食材自备或在预约时选择代买。最终费用以下单报价为准。</Text>{chef.packages.map((p:R)=><View className="service-option" key={p.id}><Text className="heading">{p.name}</Text><Text className="scope-copy">{p.description}</Text><View className="section-row"><Text className="price">{money(p.serviceFen)}</Text><Button size="mini" className="primary" onClick={()=>onBook(p)}>预约这份服务</Button></View></View>)}{!chef.packages.length&&<Text className="hint">暂无可预约套餐</Text>}</View><View id="chef-about" className="card anchor-section"><Text className="heading">擅长的家常味</Text><Text>{chef.cuisines.join('、')}</Text><Text>{chef.bio||'服务者尚未填写介绍'}</Text><Text className="heading">服务范围</Text><Text>以预约地址和档期校验为准，服务半径约 {Math.round(chef.serviceRadiusM/1000)} 公里。</Text><Text className="hint">请结合服务介绍与实际评价选择；保险服务尚未开通。</Text></View><View className="card"><Text className="heading">用户评价</Text>{reviews===null?<Text className="hint">正在加载评价…</Text>:reviews.length?reviews.map((r,i)=><View className="review" key={i}><Text>味道 {r.taste} · 服务 {r.service} · 守时 {r.punctuality}</Text><Text>{r.body}</Text>{r.followup&&<Text>追评：{r.followup}</Text>}</View>):<Text className="hint">还没有评价</Text>}</View>
 </>;
}