import {useEffect,useState} from 'react';
import {View,Text,Button,Input,Switch} from '@tarojs/components';
import Taro from '@tarojs/taro';
import {api,money,dateText} from '../../api';
declare const wx:any;
const labels:Record<string,string>={REQUESTED:'待财务审核',APPROVED:'审核通过',PROCESSING:'处理中',ACCEPTED:'微信已受理',WAIT_USER_CONFIRM:'待确认收款',TRANSFERING:'转账中',CANCELING:'撤销中',SUCCESS:'已到账',FAIL:'失败，余额已退回',CANCELLED:'已取消，余额已退回',REJECTED:'未通过，余额已退回',REVIEW_REQUIRED:'需财务核对',AVAILABLE:'已计入余额',PAID:'已分账到账',ATTENTION:'需财务处理',SETTLED:'已结算',PENDING:'待结算',FROZEN:'暂停结算'};
export function ChefIncome(){
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState(''),[name,setName]=useState(''),[consent,setConsent]=useState(false);
 const refresh=async()=>setData(await api('/chef/wallet'));
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 const run=async(fn:()=>Promise<any>)=>{if(busy)return;setBusy(true);setError('');try{await fn();await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const bind=async()=>{if(process.env.TARO_ENV!=='weapp')throw new Error('请在微信小程序绑定本人收款账户');const result=await Taro.login();await api('/auth/wechat/bind',{code:result.code});await api('/chef/payout-profile',{name,consent});setName('');setConsent(false);await Taro.showToast({title:'收款资料已保存',icon:'none'});};
 const withdraw=async()=>{if(!/^\d+(\.\d{1,2})?$/.test(amount))throw new Error('请输入最多两位小数的提现金额');const fen=Math.round(Number(amount)*100),storageKey='withdraw:'+data.chefId+':'+fen;let key=Taro.getStorageSync(storageKey);if(!key){key=Date.now().toString(36)+Math.random().toString(36).slice(2);Taro.setStorageSync(storageKey,key);}await api('/chef/withdrawals',{amountFen:fen,idempotencyKey:key});Taro.removeStorageSync(storageKey);setAmount('');};
 const confirm=async(id:string)=>{const w=await api('/chef/withdrawals/'+id+'/status',{});if(w.confirmation){if(process.env.TARO_ENV!=='weapp')throw new Error('请在微信小程序确认收款');if(typeof wx==='undefined'||!wx.canIUse('requestMerchantTransfer'))throw new Error('请升级微信后确认收款');await new Promise<void>((resolve,reject)=>wx.requestMerchantTransfer({...w.confirmation,success:()=>resolve(),fail:()=>reject(new Error('尚未确认收款，可稍后再次操作'))}));await api('/chef/withdrawals/'+id+'/status',{});}};
 return <View className="card"><Text className="heading">我的收入</Text>{error&&<Text className="error">{error}</Text>}{data&&<><Text className="price">可提现 {money(data.availableFen)}</Text><Text>提现处理中 {money(data.pendingWithdrawalFen)} · 已提现到账 {money(data.paidWithdrawalFen)}</Text><Text className="hint">订单完成、费用结清且售后保护期（{data.holdHours/24}天）结束后，由财务结算。微信直接分账的收入不会重复进入余额。</Text><Text className="heading">微信实名收款资料</Text><Input placeholder="本人微信实名姓名" value={name} onInput={e=>setName(e.detail.value)}/><View className="row"><Text>同意向微信提交资料校验收款身份</Text><Switch checked={consent} onChange={e=>setConsent(e.detail.value)}/></View><Button disabled={busy||!name.trim()||!consent} onClick={()=>void run(bind)}>绑定本人微信收款</Button>{data.transferEnabled?<><Input type="digit" placeholder="提现金额（元）" value={amount} onInput={e=>setAmount(e.detail.value)}/><Button className="primary" disabled={busy||!amount} onClick={()=>void run(withdraw)}>申请微信提现</Button></>:<Text className="hint">微信提现渠道尚未开通，余额会保留。</Text>}<Text className="heading">提现记录</Text>{!data.withdrawals.length&&<Text className="hint">暂无提现记录</Text>}{data.withdrawals.map((w:any)=><View className="chat-message" key={w.id}><Text>{money(w.amountFen)} · {labels[w.status]??w.status}</Text><Text className="hint">{dateText(w.createdAt)}{w.reason?' · '+w.reason:''}</Text>{w.status==='REQUESTED'?<Button size="mini" disabled={busy} onClick={()=>void run(()=>api('/chef/withdrawals/'+w.id,{action:'cancel'}))}>取消申请</Button>:!['SUCCESS','FAIL','CANCELLED','REJECTED'].includes(w.status)&&<Button size="mini" disabled={busy} onClick={()=>void run(()=>confirm(w.id))}>{w.status==='WAIT_USER_CONFIRM'?'确认微信收款':'查询到账结果'}</Button>}</View>)}<Text className="heading">结算记录</Text>{data.settlements.map((s:any)=><View className="chat-message" key={s.id}><Text>收入 {money(s.chefFen)} · 平台佣金 {money(s.commissionFen)}</Text><Text>{s.mode==='PROFITSHARING'?'微信直接分账':'余额结算'} · {labels[s.status]??s.status}</Text></View>)}{data.pendingOrders.map((o:any)=><Text className="hint" key={o.id}>订单 {o.id.slice(-8)} · {labels[o.status]??o.status}{o.eligibleAt?' · 保护期至 '+dateText(o.eligibleAt):''}</Text>)}</>}<Button size="mini" disabled={busy} onClick={()=>void run(refresh)}>更新收入记录</Button></View>;
}