import { randomUUID } from 'node:crypto';
import { calculateOrderAmounts, markPaymentSucceeded, type PaymentChoice } from '@home-chef/domain';

export interface QuoteRecord { id: string; customerId: string; chefId: string; packageId?: string; totalFen: number; depositFen: number; balanceFen: number; ruleVersion: string; expiresAt: string; status: 'ACTIVE' | 'PAID' | 'EXPIRED' | 'CANCELLED'; }
export interface OrderRecord { id: string; quoteId: string; customerId: string; chefId?: string; totalFen: number; depositFen: number; balanceFen: number; receivedFen: number; refundedFen: number; contractStatus: 'PENDING_ACCEPTANCE' | 'ACCEPTED' | 'CANCELLED'; paymentStatus: 'DEPOSIT_PAID' | 'FULLY_PAID' | 'FULLY_REFUNDED'; createdAt: string; acceptedAt?: string; cancelledAt?: string; }
export interface PaymentRecord { id: string; orderId: string; kind: 'DEPOSIT' | 'FULL_PAYMENT'; amountFen: number; idempotencyKey: string; provider: string; providerRef: string; status: 'SUCCEEDED' | 'REFUNDED'; createdAt: string; }
export interface OutboxRecord { id: string; eventType: string; aggregateType: string; aggregateId: string; payload: Record<string, unknown>; occurredAt: string; publishedAt?: string; }
export interface CandidateRecord { orderId: string; chefId: string; distanceM: number; status: 'INVITED' | 'ACCEPTED' | 'DECLINED'; }

export class MvpStore {
  readonly quotes = new Map<string, QuoteRecord>(); readonly orders = new Map<string, OrderRecord>(); readonly payments = new Map<string, PaymentRecord>(); readonly candidates: CandidateRecord[] = []; readonly outbox: OutboxRecord[] = []; private readonly idempotency = new Map<string, string>();
  private event(eventType: string, aggregateType: string, aggregateId: string, payload: Record<string, unknown>): void { this.outbox.push({ id: randomUUID(), eventType, aggregateType, aggregateId, payload, occurredAt: new Date().toISOString() }); }
  createQuote(input: { customerId: string; chefId: string; packageId?: string; totalFen: number; expiresAt?: string }): QuoteRecord {
    const amounts = calculateOrderAmounts({ totalFen: input.totalFen, paymentChoice: 'DEPOSIT' });
    const quote: QuoteRecord = { id: randomUUID(), customerId: input.customerId, chefId: input.chefId, packageId: input.packageId, ...amounts, ruleVersion: 'mvp-2026-09-11', expiresAt: input.expiresAt ?? new Date(Date.now() + 30 * 60_000).toISOString(), status: 'ACTIVE' };
    this.quotes.set(quote.id, quote); this.event('QuoteCreated', 'Quote', quote.id, { customerId: quote.customerId, chefId: quote.chefId, totalFen: quote.totalFen }); return quote;
  }
  payQuote(quoteId: string, paymentChoice: PaymentChoice, idempotencyKey: string): OrderRecord {
    const previousOrderId = this.idempotency.get(idempotencyKey); if (previousOrderId) return this.orders.get(previousOrderId)!;
    const quote = this.quotes.get(quoteId); if (!quote) throw new HttpError(404, 'QUOTE_NOT_FOUND', '报价不存在');
    if (quote.status !== 'ACTIVE') throw new HttpError(409, 'QUOTE_NOT_ACTIVE', '报价已失效或已支付');
    if (Date.parse(quote.expiresAt) <= Date.now()) { quote.status = 'EXPIRED'; throw new HttpError(409, 'QUOTE_EXPIRED', '报价已过期'); }
    const receivedFen = paymentChoice === 'FULL_PAYMENT' ? quote.totalFen : quote.depositFen;
    markPaymentSucceeded('PENDING_PAYMENT', paymentChoice);
    const order: OrderRecord = { id: randomUUID(), quoteId: quote.id, customerId: quote.customerId, chefId: quote.chefId, totalFen: quote.totalFen, depositFen: quote.depositFen, balanceFen: paymentChoice === 'FULL_PAYMENT' ? 0 : quote.balanceFen, receivedFen, refundedFen: 0, contractStatus: 'PENDING_ACCEPTANCE', paymentStatus: paymentChoice === 'FULL_PAYMENT' ? 'FULLY_PAID' : 'DEPOSIT_PAID', createdAt: new Date().toISOString() };
    const payment: PaymentRecord = { id: randomUUID(), orderId: order.id, kind: paymentChoice, amountFen: receivedFen, idempotencyKey, provider: 'sandbox', providerRef: `sandbox_${randomUUID()}`, status: 'SUCCEEDED', createdAt: order.createdAt };
    quote.status = 'PAID'; this.orders.set(order.id, order); this.payments.set(payment.id, payment); this.idempotency.set(idempotencyKey, order.id); this.event('OrderPaymentSucceeded', 'Order', order.id, { paymentId: payment.id, amountFen: receivedFen, paymentChoice }); return order;
  }
  acceptOrder(orderId: string, chefId: string): OrderRecord { const order = this.getOrder(orderId); if (order.contractStatus !== 'PENDING_ACCEPTANCE') throw new HttpError(409, 'ORDER_NOT_ACCEPTABLE', '订单当前不可接单'); if (order.chefId && order.chefId !== chefId) throw new HttpError(403, 'CHEF_NOT_INVITED', '厨师不在订单候选中'); order.chefId = chefId; order.contractStatus = 'ACCEPTED'; order.acceptedAt = new Date().toISOString(); this.event('ChefAcceptedOrder', 'Order', order.id, { chefId }); return order; }
  inviteCandidates(orderId: string, candidates: Array<{ chefId: string; distanceM: number }>): CandidateRecord[] { const order = this.getOrder(orderId); if (order.contractStatus !== 'PENDING_ACCEPTANCE') throw new HttpError(409, 'ORDER_NOT_MATCHABLE', '订单当前不可派单'); const unique = new Map(candidates.map((candidate) => [candidate.chefId, candidate])); if (unique.size > 3) throw new HttpError(400, 'MATCH_CANDIDATE_LIMIT', '最多推荐3位厨师'); if ([...unique.values()].some((candidate) => !candidate.chefId || !Number.isFinite(candidate.distanceM) || candidate.distanceM < 0)) throw new HttpError(400, 'INVALID_CANDIDATE', '候选厨师或距离无效'); const rows = [...unique.values()].map((candidate) => ({ orderId, chefId: candidate.chefId, distanceM: candidate.distanceM, status: 'INVITED' as const })); for (const row of this.candidates.filter((item) => item.orderId === orderId && item.status === 'INVITED')) row.status = 'DECLINED'; this.candidates.push(...rows); this.event('ChefsMatched', 'Order', orderId, { candidateCount: rows.length }); return rows; }
  claimCandidate(orderId: string, chefId: string): OrderRecord { const order = this.getOrder(orderId); if (order.contractStatus !== 'PENDING_ACCEPTANCE') throw new HttpError(409, 'ORDER_ALREADY_CLAIMED', '订单已被其他厨师接单'); const candidate = this.candidates.find((item) => item.orderId === orderId && item.chefId === chefId && item.status === 'INVITED'); if (!candidate) throw new HttpError(403, 'CHEF_NOT_INVITED', '厨师不在订单候选中'); for (const item of this.candidates) if (item.orderId === orderId) item.status = item === candidate ? 'ACCEPTED' : 'DECLINED'; order.chefId = chefId; order.contractStatus = 'ACCEPTED'; order.acceptedAt = new Date().toISOString(); this.event('ChefAcceptedOrder', 'Order', orderId, { chefId, matched: true }); return order; }
  cancelOrder(orderId: string): OrderRecord { const order = this.getOrder(orderId); if (order.contractStatus === 'CANCELLED') return order; if (order.contractStatus !== 'PENDING_ACCEPTANCE' && order.contractStatus !== 'ACCEPTED') throw new HttpError(409, 'ORDER_NOT_CANCELLABLE', '订单当前不可取消'); order.contractStatus = 'CANCELLED'; order.refundedFen = order.receivedFen; order.receivedFen = 0; order.paymentStatus = 'FULLY_REFUNDED'; order.cancelledAt = new Date().toISOString(); for (const payment of this.payments.values()) if (payment.orderId === order.id && payment.status === 'SUCCEEDED') payment.status = 'REFUNDED'; this.event('OrderCancelledAndRefunded', 'Order', order.id, { refundedFen: order.refundedFen }); return order; }
  expirePendingAcceptance(now = Date.now(), timeoutMs = 5 * 60_000): OrderRecord[] { const expired: OrderRecord[] = []; for (const order of this.orders.values()) if (order.contractStatus === 'PENDING_ACCEPTANCE' && Date.parse(order.createdAt) + timeoutMs <= now) expired.push(this.cancelOrder(order.id)); return expired; }
  getOrder(orderId: string): OrderRecord { const order = this.orders.get(orderId); if (!order) throw new HttpError(404, 'ORDER_NOT_FOUND', '订单不存在'); return order; }
}
export class HttpError extends Error { constructor(public readonly status: number, public readonly code: string, message: string) { super(message); } }
